dataset: rat_bench
data_in: data/rat_bench
annotations_in:
  - ../../../netscratch/yay/_ext_outputs/rat_bench
tri:
  universal_tri_pipeline: ../../../netscratch/yay/tri_pipelines/rat_bench_nobart/_checkpoints/full/full_model_1
  max_length: 512
mask_token: "[MASK]"
output:
  format: jsonl
  file: logs/privacy/rat_bench/full_nobart_model_1.jsonl
progress: false
