params:
  ks: ["*"]

explainer:
  name: shap
  tri_pipeline: ../../../netscratch/yay/tri_pipelines/yelp/_checkpoints/yelp__deid__lr5e-5

precomputation:
  risk_scores: data/yelp/yelp_risk_shap.jsonl
  result_in: ../../../netscratch/yay/_ext_outputs/yelp/presidio/20260210_100853_yelp_presidio.jsonl

tri_chunking:
  enabled: true

token_selection:
  name: until_k
