data: db_bio
data_in: data/db_bio
risk_in: data/db_bio/tri_risk/shap.jsonl
result_in: ../../../netscratch/yay/_ext_outputs/db_bio/presidio/{run_timestamp}_db_bio_presidio.jsonl
pipeline_in: ../../../netscratch/yay/tri_pipelines/db_bio/_checkpoints/full/full