data: db_bio
data_in: data/db_bio/test/data-00000-of-00001.arrow
result_in: outputs/db_bio/presidio/20260205_192847_db_bio_presidio.jsonl
pipeline_in: ../../../netscratch/yay/tri_pipelines/db_bio/_checkpoints/db_bio__lr5e-5
n_first_predictions: 5