data: tab
data_in: data/tab
split: indices/tab/test/50_eval/{task_id}.txt
result_in: outputs/tab/presidio/{run_timestamp}_tab_presidio_task_{task_id}.jsonl
save_to_jsonl: data/tab/tri_preprocessing/50_eval_deid_{task_id}.jsonl
