data: tab
data_in: data/tab
split: indices/tab/test/500_random/{task_id}.txt
result_in: outputs/tab/presidio/{run_timestamp}_tab_presidio_task_{task_id}.jsonl
save_to_jsonl: data/tab/tri_preprocessing/500_random_{task_id}.jsonl