params:
  rhos: ["*"]

explainer:
  name: greedy
  tri_pipeline: ../../../netscratch/yay/tri_pipelines/reddit/reddit__lr1e-4__bs32__ft15__pre1
  risk_temperature: 0.1

precomputation:
  risk_scores: data/reddit/reddit_risk_greedy.jsonl

token_selection:
  name: by_risk