params:
  rhos: ["*"]

explainer:
  name: shap
  tri_pipeline: ../../../netscratch/yay/tri_pipelines/reddit/_checkpoints/reddit_8_16_0.0001
  risk_temperature: 0.1

precomputation:
  risk_scores: data/reddit/reddit_risk_shap.jsonl
  result_in: outputs/reddit/presidio/20260210_023708_reddit_presidio.jsonl

token_selection:
  name: by_risk