gpt2-paraphraser: models/gpt2-paraphraser
reddit:
  tri_location: models/tri_pipelines/reddit/_checkpoints
  tri_pipeline: models/tri_pipelines/reddit/new_pipeline
  tri_pipeline_no_mask: models/tri_pipelines/reddit/old_pipeline
  result_in: outputs/reddit/presidio/20251228_165756_reddit_presidio.jsonl
tab:
  tri_location: models/tri_pipelines/tab/_checkpoints
  tri_pipeline: models/tri_pipelines/tab/new_pipeline
  tri_pipeline_no_mask: models/tri_pipelines/tab/old_pipeline
  result_in: outputs/tab/presidio/20251228_165931_tab_presidio.jsonl
  pii_annotator: models/pii_detectors/tab/new_detector