params:
  epsilon: "*"
  ks: ["*"]

explainer:
  name: greedy
  tri_pipeline: models/tri_pipelines/reddit/20251110_190043
  risk_temperature: 0.1

precomputation:
  risk_scores: data/reddit/reddit_risk_greedy.jsonl

starting_anonymizations:
  - outputs/reddit/presidio/20251216_160413_reddit_presidio.jsonl

tri_chunking:
  enabled: true

token_selection:
  name: until_k
  sort_by_risk: false