params:
  epsilon: "*"
  ks: ["*"]

explainer:
  name: shap
  tri_pipeline: models/tri_pipelines/reddit/20251110_190043
  risk_temperature: 0.1

precomputation:
  risk_scores: data/reddit/reddit_risk_shap_v2.jsonl
  result_in: outputs/reddit/presidio/20251228_162201_reddit_presidio_v2.jsonl

tri_chunking:
  enabled: true

token_selection:
  name: until_k