params:
  rhos: ["*"]

explainer:
  name: shap
  tri_pipeline: ../../../netscratch/yay/tri_pipelines/reddit/reddit__lr5e-5
  risk_temperature: 0.1

precomputation:
  risk_scores: data/reddit/reddit_risk_shap.jsonl

token_selection:
  name: by_risk