params:
  rhos: ["*"]

explainer:
  name: shap
  tri_pipeline: ../../../netscratch/yay/tri_pipelines/db_bio/_checkpoints/task_{task_id}/db_bio__deid__lr5e-5__task_{task_id}
  risk_temperature: 0.1

precomputation:
  risk_scores: data/db_bio/db_bio_risk_shap.jsonl
  result_in: outputs/db_bio/presidio/{run_timestamp}_db_bio_presidio_task_{task_id}.jsonl

token_selection:
  name: by_risk