data: db_bio
data_in: data/db_bio
split: indices/db_bio/test/50_eval/{task_id}.txt
result_in: outputs/db_bio/presidio/{run_timestamp}_db_bio_presidio_task_{task_id}.jsonl
save_to_jsonl: data/db_bio/tri_preprocessing/50_eval_deid_{task_id}.jsonl
