data: db_bio
data_in: data/db_bio
split: indices/db_bio/test.txt
result_in: ../../../netscratch/yay/_ext_outputs_subset/db_bio/presidio/{run_timestamp}_db_bio_presidio.jsonl
save_to_jsonl: data/db_bio/tri_preprocessing/exact_deid.jsonl
