params:
  epsilon: "*"
  ks: ["*"]

explainer:
  name: shap
  tri_pipeline: ../../../netscratch/yay/tri_pipelines/db_bio/_checkpoints/500_random_{task_id}/500_random_{task_id}__task_{task_id}
  risk_temperature: 0.1

precomputation:
  risk_scores: data/db_bio/tri_risk/shap_{task_id}.jsonl
  result_in: ../../../netscratch/yay/_ext_outputs/db_bio/presidio/{run_timestamp}_db_bio_presidio_task_{task_id}.jsonl

tri_chunking:
  enabled: true

token_selection:
  name: until_k