params:
  epsilon: "*"

explainer:
  name: shap
  tri_pipeline: ../../../netscratch/yay/tri_pipelines/reddit/reddit__lr5e-5__eval
  risk_temperature: 0.1

precomputation:
  risk_scores: data/reddit/reddit_risk_shap.jsonl
  result_in: outputs/reddit/presidio/20260121_170408_reddit_presidio.jsonl

tri_chunking:
  enabled: true
