dataset: db_bio
data_in: data/db_bio
split: indices/db_bio/test/50_eval/{task_id}.txt
annotations_in:
  - outputs/db_bio
metric:
  type: cosine
  vectorizer:
    type: sentence
    model_name: sentence-transformers/all-MiniLM-L6-v2
output:
  format: jsonl
  file: logs/db_bio_div_cosine_exp_task_{task_id}.jsonl
