dataset: db_bio
data_in: data/db_bio
annotations_in:
  - ../../../netscratch/yay/_ext_outputs/db_bio
metric:
  type: cosine
  vectorizer:
    type: sentence
    model_name: sentence-transformers/all-MiniLM-L6-v2
output:
  format: jsonl
  file: logs/divergence/db_bio/cosine.jsonl
