dataset: db_bio
data_in: data/db_bio
split: indices/db_bio/test.txt
annotations_in:
  - ../../../netscratch/yay/_ext_outputs/db_bio/dpmlm
  - ../../../netscratch/yay/_ext_outputs/db_bio/petre
metric:
  type: pp
output:
  format: jsonl
  file: logs/divergence/db_bio/pp_subset.jsonl
