data: tab
data_in: data/tab
split: indices/tab/test/50_eval/{task_id}.txt
result_in: outputs/tab/presidio/{run_timestamp}_tab_presidio_task_{task_id}.jsonl
pipeline_in: ../../../netscratch/yay/tri_pipelines/tab/_checkpoints/50_eval_{task_id}/50_eval_{task_id}__task_{task_id}
n_first_predictions: 10