params:
  ks: ["*"]

explainer:
  name: greedy
  tri_pipeline: ../../../netscratch/yay/tri_pipelines/reddit/20251203_135444

precomputation:
  risk_scores: data/reddit/reddit_risk_greedy.jsonl

mask_text: "[MASK]"

starting_anonymizations:
  - outputs/reddit/spacy/20251213_165323_reddit_spacy.jsonl

tri_chunking:
  enabled: false
