params:
  ks: ["*"]

explainer:
  name: greedy
  tri_pipeline: ../../../netscratch/yay/tri_pipelines/reddit/reddit__lr1e-4__bs32__ft15__pre1

precomputation:
  risk_scores: data/reddit/reddit_risk_greedy.jsonl

starting_anonymizations:
  - outputs/reddit/presidio/20251213_165316_reddit_presidio.jsonl

tri_chunking:
  enabled: false
