dataset: tab
data_in: data/TAB/splitted/test.json
debug: true
annotations_in:
  - outputs/tab
target:
  key: year_group
  type: ordinal
  enum:
    - 1975-1995
    - 1996-1998
    - 1999-2001
    - 2002-2004
    - 2005-2007
    - 2008-2010
    - 2011-2013
    - 2014-2019
split:
  - train: 0.0
    val: 1.0
  - path: data/TAB/splitted/train.json
    train: 1.0
    val: 0.0
  - path: data/TAB/splitted/dev.json
    train: 0.0
    val: 1.0
random_state: 42
head:
  type: bert_ordinal
  params:
    epochs: 2
    init_checkpoint: ../../../netscratch/yay/tri_pipelines/tab/_checkpoints/tab__lr5e-5/finetuning/checkpoint-2310
    checkpoint_dir: ../../../netscratch/yay/util_tri_pipelines/tab/year
    primary_metric: macro_mae
    encoder_lr: 1e-6
    head_lr: 5e-4
    early_stop_patience: 2
output:
  format: jsonl
  file: logs/tab_year_exp.jsonl
