params:
  ks: ["*"]

explainer:
  name: shap
  tri_pipeline: models/tri_pipelines/reddit/20251110_190043

precomputation:
  risk_scores: data/reddit/reddit_risk_shap.jsonl

starting_anonymizations:
  - outputs/reddit/presidio/20251216_160413_reddit_presidio.jsonl

tri_chunking:
  enabled: false

token_selection:
  name: until_k
