dataset: reddit
data_in: data/reddit/reddit.jsonl
explainer: shap
explainer_in: ../../../netscratch/yay/tri_pipelines/reddit/_checkpoints/reddit__deid__lr5e-5
result_in: outputs/reddit/presidio/20260210_023708_reddit_presidio.jsonl
save_to_jsonl: data/reddit/reddit_risk_shap.jsonl
sort_by: scores
offset_mode: original
