dataset_sets:
  - names: 
    - name: tab
      print_as: "TAB"
    - name: db_bio
      print_as: "DB-Bio"
    scores: 
      - name: privacy_exact_mean_reciprocal_rank
        rename_as: P_exact
        best: 0
        worst: 1
      - name: privacy_more_mean_reciprocal_rank
        rename_as: P_more
        best: 0
        worst: 1
      - name: privacy_full_mean_reciprocal_rank
        rename_as: P_full
        best: 0
        worst: 1
      - name: privacy_exact_accuracy
        rename_as: TRIR_exact
        best: 0
        worst: 1
      - name: privacy_more_accuracy
        rename_as: TRIR_more
        best: 0
        worst: 1
      - name: privacy_full_accuracy
        rename_as: TRIR_full
        best: 0
        worst: 1
      - name: utility_utility_nominal_raw_acc
        rename_as: U_nominal_acc
        best: 1
        worst: 0
      - name: utility_utility_ordinal_raw_mae
        rename_as: U_ordinal_mae
        best: 0
        worst: 1
      - name: supervised_divergence_utility_nominal_raw_acc
        rename_as: SD_nominal_acc
        best: 1
        worst: 0
      - name: supervised_divergence_utility_ordinal_raw_mae
        rename_as: SD_ordinal_mae
        best: 0
        worst: 1
      - name: runtime_avg_anon_time_s
        rename_as: T_anon_avg_s
        best: 0
        worst: float("inf")
      - name: divergence_bertscore
        rename_as: D_bertscore
        best: 0
        worst: 1
        exclude:
          - baseline
      - name: divergence_cosine
        rename_as: D_cosine
        best: 0
        worst: 1
        exclude:
          - baseline
      - name: divergence_pp
        rename_as: D_pp
        best: 0
        worst: 1
        exclude: 
          - baseline
          - spacy
          - presidio
          - manual
          - baroud
