dataset_sets:
  - names: ["tab", "db_bio"]
    scores: 
      - name: privacy_exact_mean_reciprocal_rank
        rename_as: P_exact
        best: 0
        worst: 1
      - name: privacy_more_mean_reciprocal_rank
        rename_as: P_more
        best: 0
        worst: 1
      - name: utility_utility_nominal_weighted_score
        rename_as: U_nominal
        best: 1
        worst: 0
      - name: utility_utility_ordinal_weighted_score
        rename_as: U_ordinal
        best: 1
        worst: 0
      - name: supervised_divergence_utility_nominal_weighted_score
        rename_as: SD_nominal
        best: 1
        worst: 0
      - name: supervised_divergence_utility_ordinal_weighted_score
        rename_as: SD_ordinal
        best: 1
        worst: 0
      - name: divergence_bertscore
        rename_as: D_bertscore
        best: 0
        worst: 1
      - name: divergence_cosine
        rename_as: D_cosine
        best: 0
        worst: 1