methods: &methods
  - method: presidio
    print_as: "Presidio"
  - method: petre
    print_as: "PETRE with Presidio-deid"
    params_one_run: [k]
  - method: dpmlm_uniform
    print_as: "DPMLM"
    params: [epsilon]
  - method: dpmlm_shap
    params: [epsilon]
    print_as: "Risk-aware DPMLM"
  - method: dpmlm_shap_masked
    params: [epsilon]
    print_as: "Risk-aware DPMLM with Presidio-deid"
  - method: dpmlm_shap_unsorted
    params: [epsilon]
    params_one_run: [k]
    print_as: "Risk-aware k-DPMLM with Presidio-deid"
  - method: dpmlm_shap
    params: [epsilon]
    params_one_run: [k]
    print_as: "Risk-aware k-DPMLM with Presidio-deid sorted by risk"

datasets:
  reddit:
    data_in: data/reddit/reddit.jsonl
  tab:
    data_in: data/TAB/splitted/test.json

experiments:
  - name: privacy_reddit
    dataset: reddit
    method_class: privacy
    files:
      - type: privacy
        file: visualize/pretty/privacy.json
    methods: *methods
  - name: privacy_tab
    dataset: tab
    method_class: privacy
    files:
      - type: privacy
        file: visualize/pretty/privacy_tab.json
    methods: *methods
