method_sets:
  - name: "simple_maskers"
    print_as: "Baseline methods with or without thresholds"
    methods:
      - method: "baseline"
        print_as: "Original"
      - method: "presidio"
        print_as: "Presidio"
      - method: "spacy"
        print_as: "SpaCy"
      - method: "manual"
        print_as: "Manual"
        datasets: ["tab"]
      - method: "baroud"
        print_as: "NER-based masking"
        params_one_run: {"lambda": [0.5, 0.9]}
        datasets: ["tab"]
      - method: "petre_shap"
        print_as: "PETRE + Presidio"
        params_one_run: {"k": [2, 3, 5, 7, 10]}
  - name: "risk_maskers"
    print_as: "Risk-based masking with varying rho"
    methods:
      - method: "baseline"
        print_as: "Original"
      - method: "risk_shap"
        print_as: "Risk-based masking + Presidio"
        params_one_run: {"rho": [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}
  - name: "record_level_rewriters"
    print_as: "DP Record-level rewriting methods with varying epsilon"
    methods:
      - method: "baseline"
        print_as: "Original"
      - method: "dpbart"
        print_as: "DP-BART"
        params: ["epsilon"]
      - method: "dpparaphrase"
        print_as: "DP-Paraphrase"
        params: ["epsilon"]
      - method: "dpprompt"
        print_as: "DP-Prompt"
        params: ["epsilon"]
  - name: "token_level_rewriters"
    print_as: "DP Token-level rewriting methods with varying epsilon"
    methods:
      - method: "baseline"
        print_as: "Original"
      - method: "dpmlm_uniform"
        print_as: "DP-MLM"
        params: ["epsilon"]
      - method: "dpmlm_shap_no_presidio"
        print_as: "Risk-Aware DP-MLM"
        params: ["epsilon"]
      - method: "dpmlm_shap"
        print_as: "Risk-Aware DP-MLM + Presidio"
        params: ["epsilon"]
  - name: "token_level_rewriters_with_threshold_k"
    print_as: "DP Token-level rewriting methods with varying epsilon and limiting hyperparameter k"
    methods:
      - method: "baseline"
        print_as: "Original"
      - method: "dpmlm_shap"
        print_as: "Risk-Aware DP-MLM + Presidio"
        params: ["epsilon"]
      - method: "dpmlm_shap"
        print_as: "Risk-Aware k-DP-MLM + Presidio"
        params: ["epsilon"]
        params_one_run: {"k": [2, 3, 5, 7, 10]}
  - name: "token_level_rewriters_with_threshold_lambda"
    datasets: ["tab"]
    print_as: "DP Token-level rewriting methods with varying epsilon and limiting hyperparameter lambda"
    methods:
      - method: "baseline"
        print_as: "Original"
      - method: "dpmlm_shap"
        print_as: "Risk-Aware DP-MLM + Presidio"
        params: ["epsilon"]
      - method: "dpmlm_shap"
        print_as: "Risk-Aware λ-DP-MLM + Presidio"
        params: ["epsilon"]
        params_one_run: {"lambda": [0.5, 0.9]}
  - name: "token_level_rewriters_with_threshold_rho"
    print_as: "DP Token-level rewriting methods with varying epsilon and limiting hyperparameter rho"
    methods:
      - method: "baseline"
        print_as: "Original"
      - method: "dpmlm_shap"
        print_as: "Risk-Aware DP-MLM + Presidio"
        params: ["epsilon"]
      - method: "dpmlm_shap"
        print_as: "Risk-Aware ρ-DP-MLM + Presidio"
        params_one_run: ["epsilon"]
        params: {"rho": [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}