dataset: tab
data_path: data/TAB/splitted/test.json
attacker_extensions: data/TAB/test_bk_sum.jsonl
model_name: roberta-base
output_root: ../../../netscratch/yay/tri_pipelines/tab/_checkpoints/s3
max_records: null
max_length: 512
device: cpu

training:
  finetuning_epochs: 15
  batch_size: 8
  use_pretraining: true
  pretraining_epochs: 1
  per_step: null
  early_stop_threshold: null
