params:
  epsilon: "*"

explainer:
  name: shap
  tri_pipeline: ../../../netscratch/yay/tri_pipelines/yelp/_checkpoints/full/full
  risk_temperature: 0.1

precomputation:
  risk_scores: data/yelp/tri_risk/shap.jsonl
  result_in: ../../../netscratch/yay/_ext_outputs/yelp/presidio/{run_timestamp}_yelp_presidio.jsonl

dpmlm_chunking:
  enabled: true
  max_tokens: 256
  overlap_tokens: 128
