compensate_epsilon: false
add_probability: 0.0
delete_probability: 0.0

pii_annotator: null
pii_threshold: null

explainability: greedy
explainer_path: models/tri_pipelines/reddit/20251021_110954

pii_chunking:
  enabled: false
  max_length: 512
  overlap: 50

tri_chunking:
  enabled: true
  max_length: 512

dpmlm_chunking:
  enabled: true
  max_length: 512
