requires_idx: false

pii_annotator: models/pii_detectors/20251017_185749
pii_threshold: 0.7

explainability: uniform
explainer: models/tri_pipelines

pii_chunking:
  enabled: false
  max_length: 512
  overlap: 50

tri_chunking:
  enabled: false
  max_length: 512

dpmlm_chunking:
  enabled: false
  max_length: 512

# Model parameters (can be overridden in code)
# model_checkpoint: "roberta-base"
# clip_min: -3.2093127
# clip_max: 16.304797887802124
# k_candidates: 5
# use_temperature: true