requires_idx: false
uses_filtering: true
uses_scoring: true
compensate_epsilon: false

pii_annotator: models/pii_detectors/tab/20251019_140402
pii_threshold: 0.7

explainability: greedy
explainer_path: models/tri_pipelines/tab/20251018_201114

pii_chunking:
  enabled: false
  max_length: 512
  overlap: 50

tri_chunking:
  enabled: false
  max_length: 512

dpmlm_chunking:
  enabled: false
  max_length: 512

# Model parameters (can be overridden in code)
# model_checkpoint: "roberta-base"
# clip_min: -3.2093127
# clip_max: 16.304797887802124
# k_candidates: 5
# use_temperature: true