compensate_epsilon: false
add_probability: 0.0
delete_probability: 0.0

pii_annotator: models/pii_detectors/tab/20251021_093003
pii_threshold: 0.7

explainability: greedy
explainer_path: models/tri_pipelines/tab/20251020_223625

pii_chunking:
  enabled: true
  max_length: 512
  overlap: 50

tri_chunking:
  enabled: true
  max_length: 512

dpmlm_chunking:
  enabled: true
  max_length: 512
