# starting_annotations is handled at top-level via --annotations_in

explainability: greedy
# explainer_path: models/tri_pipelines/tab/20251018_201114
explainer_path: models/tri_pipelines/trustpilot/20251020_110945

mask_text: "[MASK]"

tri_chunking:
  enabled: false
  max_length: 512