# starting_annotations is now handled at top-level via --load_annotations
# Remove this field and use: --load_annotations dataset:model:timestamp

explainability: greedy
explainer_path: models/tri_pipelines/tab/20251018_201114

mask_text: "[MASK]"

tri_chunking:
  enabled: false
  max_length: 512