requires_idx: true
requires_dataset: true
uses_annotations: true
uses_scoring: true
requires_non_uniform_explainer: true

starting_annotations: null

explainability: greedy
explainer_path: models/tri_pipelines/tab/20251018_201114

mask_text: "[MASK]"

tri_chunking:
  enabled: false
  max_length: 512