dataset: db_bio
data_in: data/db_bio
split: indices/db_bio/test/50_eval/{task_id}.txt
debug: true
annotations_in:
- outputs/db_bio
target:
  key: label
  type: nominal
random_state: 42
head:
  type: bert_classifier
  params:
    epochs: 5
    init_checkpoint: ../../../netscratch/yay/tri_pipelines/db_bio/_checkpoints/500_random_{task_id}/500_random_{task_id}__task_{task_id}/finetuning/{checkpoint}
    checkpoint_dir: ../../../netscratch/yay/util_tri_pipelines/db_bio/label_internal_utility
    primary_metric: macro_f1
    encoder_lr: 1e-6
    head_lr: 1e-4
    early_stop_patience: 2
    save_checkpoints: false
output:
  format: jsonl
  file: logs/utility/db_bio/label_task_{task_id}.jsonl
protocol: internal_utility
internal_utility:
  n_folds: 50
  random_state: '{task_id}'
vectorizer:
  type: text
task_id: '{task_id}'
