dataset: db_bio
data_in: data/db_bio
split: indices/db_bio/test/50_eval/{task_id}.txt
debug: true
annotations_in:
- outputs/db_bio
target:
  key: label
  type: nominal
random_state: 42
head:
  type: logistic_classifier
  params:
    max_iter: 500
    class_weight: balanced
    n_jobs: -1
    primary_metric: f1
output:
output:
  format: jsonl
  file: logs/utility/db_bio/label_task_{task_id}.jsonl
protocol: internal_utility
internal_utility:
  n_folds: 50
  random_state: '{task_id}'
vectorizer:
  type: tfidf
  params:
    ngram_range:
    - 1
    - 2
    max_features: 10000
    min_df: 2
task_id: '{task_id}'
