data: reddit
data_in: data/reddit/reddit.jsonl
result_in: outputs/reddit/presidio/{run_timestamp}_reddit_presidio_task_{task_id}.jsonl
save_to_jsonl: data/reddit/tri_preprocessing/deid_{task_id}.jsonl
deidentify: true
