dataset: tab
data_in: data/tab
annotations_in:
  - ../../../netscratch/yay/_ext_outputs/tab/*iter*/*
tri:
  universal_tri_pipeline: ../../../netscratch/yay/tri_pipelines/tab/_checkpoints/full/full
  max_length: 512
mask_token: "[MASK]"
output:
  format: jsonl
  file: logs/privacy/tab/full.jsonl
progress: false
