params:
  lambdas: ["*"]

explainer:
  name: shap
  tri_pipeline: ../../../netscratch/yay/tri_pipelines/db_bio/_checkpoints/full/full
  risk_temperature: 0.1

precomputation:
  risk_scores: data/db_bio/tri_risk/shap.jsonl
  result_in: ../../../netscratch/yay/_ext_outputs/db_bio/presidio/{run_timestamp}_db_bio_presidio.jsonl

token_selection:
  name: pii_only
  pii_annotator: ../../../netscratch/yay/pii_detectors/tab/tab__lr3e-5__bs8__m_partial_recall
  pii_chunking:
    enabled: true
  pii_aggregation_strategy: none
  pii_force_non_o_prediction: true
