dataset: rat_bench
data_in: data/rat_bench
explainer: shap
explainer_in: ../../../netscratch/yay/tri_pipelines/rat_bench/_checkpoints/full_deid/full_deid
result_in: ../../../netscratch/yay/_ext_outputs/rat_bench/presidio/{run_timestamp}_rat_bench_presidio.jsonl
save_to_jsonl: data/rat_bench/tri_risk/shap.jsonl
sort_by: scores
offset_mode: original
