params:
  ks: ["*"]

explainer:
  name: shap
  tri_pipeline: ../../../netscratch/yay/tri_pipelines/tab/tab__lr1e-4__bs16__ft15__pre1

precomputation:
  risk_scores: data/TAB/test_risk_shap.jsonl

starting_anonymizations:
  - outputs/tab/presidio/20251220_095719_tab_presidio.jsonl

tri_chunking:
  enabled: false
