dataset: tab
data_path: data/TAB/tab.json
attacker_extensions: data/TAB/test_bk_sum_realistic.jsonl
model_name: roberta-large
output_root: ../../../netscratch/yay/tri_pipelines/tab/_checkpoints_realistic
max_records: null
max_length: 512

training:
  finetuning_epochs: 20
  batch_size: 8
  use_pretraining: true
  pretraining_epochs: 1
  per_step: null
  early_stop_threshold: null
  loss_type: focal
  focal_gamma: 5.0
  focal_ignore_pt: 0.95
  exclude_stopwords: true
  sensitive_selector: auto
  sensitive_selector_kwargs:
    subset_file: data/TAB/splitted/test.json
  selected_label: __SELECTED__
  other_label: __OTHER__
  p_agg: avg
