dataset: tab
data_path: data/tab
split: indices/tab/test/50_eval/{task_id}.txt
attacker_extensions: data/tab/tri_preprocessing/50_eval_deid_{task_id}.jsonl
model_name: distilbert-base-uncased
output_root: ../../../netscratch/yay/tri_pipelines/tab/_checkpoints/50_eval_deid_{task_id}
max_records: null
max_length: 512

training:
  finetuning_epochs: 10
  batch_size: 8
  use_pretraining: true
  pretraining_epochs: 1
  per_step: null
  early_stop_threshold: null
  loss_type: focal
  focal_gamma: 5.0
  focal_ignore_pt: 0.95
  exclude_stopwords: true
  p_agg: avg
  early_stop_patience: 3
