dataset: tab
data_in: data/tab
split: indices/tab/test.txt
debug: true
annotations_in:
  - ../../../netscratch/yay/_ext_outputs/tab
target:
  key: country_group
  type: nominal
source_splits:
  - val: 1.0
  - split: indices/tab/train.txt
    train: 1.0
  - split: indices/tab/val.txt
    val: 1.0
random_state: 42
head:
  type: bert_classifier
  params:
    epochs: 2
    init_checkpoint: ../../../netscratch/yay/tri_pipelines/tab/_checkpoints/exact/exact/finetuning/{checkpoint}
    checkpoint_dir: ../../../netscratch/yay/util_tri_pipelines/tab/country
    primary_metric: macro_f1
    encoder_lr: 1e-6
    head_lr: 5e-4
output:
  format: jsonl
  file: logs/supervised_divergence/tab/country.jsonl
