dataset: tab
data_in: data/tab
split: indices/tab/test/500_random/{task_id}.txt
explainer: shap
explainer_in: ../../../netscratch/yay/tri_pipelines/tab/_checkpoints/500_random_deid_{task_id}/500_random_deid_{task_id}__task_{task_id}/
result_in: ../../../netscratch/yay/_ext_outputs/tab/presidio/{run_timestamp}_tab_presidio_task_{task_id}.jsonl
save_to_jsonl: data/tab/tri_risk/shap_{task_id}.jsonl
sort_by: scores
offset_mode: original
