version: 1
results:
  utility_reddit_birth_city_country:
    dataset: reddit
    flat: reddit/utility/birth_city_country.json
  utility_reddit_age:
    dataset: reddit
    flat: reddit/utility/age.json
  utility_reddit_income_level:
    dataset: reddit
    flat: reddit/utility/income_level.json
  utility_reddit_relationship_status:
    dataset: reddit
    flat: reddit/utility/relationship_status.json
  utility_reddit_sex:
    dataset: reddit
    flat: reddit/utility/sex.json
  utility_reddit_city_country:
    dataset: reddit
    flat: reddit/utility/city_country.json
  utility_reddit_occupation:
    dataset: reddit
    flat: reddit/utility/occupation.json
  utility_reddit_education:
    dataset: reddit
    flat: reddit/utility/education.json
  utility_tab_country:
    dataset: tab
    flat: tab/utility/country.json
  utility_tab_year:
    dataset: tab
    flat: tab/utility/year.json
  privacy_reddit:
    dataset: reddit
    flat: reddit/privacy.json
  privacy_tab:
    dataset: tab
    flat: tab/privacy.json
  runtime_reddit:
    dataset: reddit
    flat: reddit/runtime.json
  runtime_tab:
    dataset: tab
    flat: tab/runtime.json
  divergence_reddit:
    dataset: reddit
    flat: reddit/divergence.json
  divergence_tab:
    dataset: tab
    flat: tab/divergence.json
