version: 1
results:
  utility_reddit_birth_city_country:
    dataset: reddit
    flat: reddit/utility/birth_city_country.json
  utility_reddit_age:
    dataset: reddit
    flat: reddit/utility/age.json
  utility_reddit_income_level:
    dataset: reddit
    flat: reddit/utility/income_level.json
  utility_reddit_relationship_status:
    dataset: reddit
    flat: reddit/utility/relationship_status.json
  utility_reddit_sex:
    dataset: reddit
    flat: reddit/utility/sex.json
  utility_reddit_city_country:
    dataset: reddit
    flat: reddit/utility/city_country.json
  utility_reddit_occupation:
    dataset: reddit
    flat: reddit/utility/occupation.json
  utility_reddit_education:
    dataset: reddit
    flat: reddit/utility/education.json
  utility_tab_country:
    dataset: tab
    flat: tab/utility/country.json
  utility_tab_year:
    dataset: tab
    flat: tab/utility/year.json
  utility_db_bio_label:
    dataset: db_bio
    flat: db_bio/utility/label.json
  privacy_reddit:
    dataset: reddit
    flat: reddit/privacy.json
  privacy_tab:
    dataset: tab
    flat: tab/privacy.json
  privacy_db_bio:
    dataset: db_bio
    flat: db_bio/privacy.json
  runtime_reddit:
    dataset: reddit
    flat: reddit/runtime.json
  runtime_tab:
    dataset: tab
    flat: tab/runtime.json
  runtime_db_bio:
    dataset: db_bio
    flat: db_bio/runtime.json
  divergence_reddit_bertscore:
    dataset: reddit
    flat: reddit/divergence/bertscore.json
  divergence_tab_bertscore:
    dataset: tab
    flat: tab/divergence/bertscore.json
  divergence_db_bio_bertscore:
    dataset: db_bio
    flat: db_bio/divergence/bertscore.json
  divergence_reddit_cosine:
    dataset: reddit
    flat: reddit/divergence/cosine.json
  divergence_tab_cosine:
    dataset: tab
    flat: tab/divergence/cosine.json
  divergence_db_bio_cosine:
    dataset: db_bio
    flat: db_bio/divergence/cosine.json
  divergence_tab_pp:
    dataset: tab
    flat: tab/divergence/pp.json
  divergence_db_bio_pp:
    dataset: db_bio
    flat: db_bio/divergence/pp.json