dataset: db_bio
data_path: data/db_bio
attacker_extensions: data/db_bio/db_bio_bk_sum_realistic.jsonl
model_name: roberta-large
output_root: ../../../netscratch/yay/tri_pipelines/db_bio/_checkpoints_realistic
max_records: null
max_length: 512

training:
  finetuning_epochs: 15
  batch_size: 16
  use_pretraining: true
  pretraining_epochs: 1
  per_step: null
  sensitive_selector: auto
  sensitive_selector_kwargs:
    subset_file: data/db_bio/test/data-00000-of-00001.arrow
  other_label: __OTHER__
  p_agg: avg
