dataset: db_bio
data_path: data/db_bio
split: indices/db_bio/test/500_random/{task_id}.txt
attacker_extensions: data/db_bio/tri_preprocessing/500_random_{task_id}.jsonl
model_name: distilbert-base-uncased
output_root: ../../../netscratch/yay/tri_pipelines/db_bio/_checkpoints/500_random_{task_id}
max_records: null
max_length: 512

training:
  finetuning_epochs: 10
  batch_size: 16
  use_pretraining: true
  pretraining_epochs: 1
  per_step: null
  p_agg: avg
  early_stop_patience: 3
