data: tab
data_in: data/tab
split: indices/tab/test/50_eval/{task_id}.txt
pipeline_in: ../../../netscratch/yay/tri_pipelines/tab/_checkpoints/50_eval_deid_{task_id}/50_eval_deid_{task_id}__task_{task_id}
n_first_predictions: 10