data: db_bio
data_in: data/db_bio
split: indices/db_bio/test/500_random/{task_id}.txt
pipeline_in: ../../../netscratch/yay/tri_pipelines/db_bio/_checkpoints/500_random_{task_id}/500_random_{task_id}__task_{task_id}
n_first_predictions: 10