add_probability: 0.0
delete_probability: 0.0

explainer:
  name: greedy
  tri_pipeline: /netscratch/yay/tri_pipelines/tab/20251201_092739
  risk_scores: data/TAB/test_risk_greedy.jsonl
  risk_temperature: 0.1

tri_chunking:
  enabled: true

token_selection:
  name: pii_only
  pii_annotator: /netscratch/yay/pii_detectors/tab/20251201_093118
  pii_threshold: 0.7

compensate_epsilon: false

pii_chunking:
  enabled: true