params:
  epsilon: "*"
  lambdas: ["05*", "09*"]

explainer:
  name: greedy
  tri_pipeline: ../../../netscratch/yay/tri_pipelines/tab/20251203_134320
  risk_temperature: 0.1

precomputation:
  risk_scores: data/TAB/test_risk_greedy.jsonl

tri_chunking:
  enabled: true

token_selection:
  name: pii_only
  pii_annotator: ../../../netscratch/yay/pii_detectors/tab/20251203_131104

pii_chunking:
  enabled: true