add_probability: 0.0
delete_probability: 0.0

explainer:
  name: greedy
  tri_pipeline: models/tri_pipelines/tab/20251104_085941
  risk_scores: data/TAB/test_risk_greedy.jsonl
  risk_temperature: 0.1

tri_chunking:
  enabled: true

token_selection:
  name: by_risk
  risk_threshold: 0.3

compensate_epsilon: false