params:
  epsilon: "*"
  rhos: ["*"]

explainer:
  name: shap
  tri_pipeline: ../../../netscratch/yay/tri_pipelines/tab/_checkpoints/tab__lr5e-5
  risk_temperature: 0.1

precomputation:
  risk_scores: data/TAB/test_risk_shap.jsonl
  result_in: outputs/tab/presidio/20260205_184512_tab_presidio.jsonl

tri_chunking:
  enabled: true

token_selection:
  name: by_risk