params:
  epsilon: "*"
  lambdas: ["*"]

explainer:
  name: shap
  tri_pipeline: ../../../netscratch/yay/tri_pipelines/tab/tab__lr5e-5
  risk_temperature: 0.1

precomputation:
  risk_scores: data/TAB/test_risk_shap.jsonl

tri_chunking:
  enabled: true

token_selection:
  name: pii_only
  pii_annotator: ../../../netscratch/yay/pii_detectors/tab/tab__lr3e-5__bs8__m_partial_recall

pii_chunking:
  enabled: true