params:
  epsilon: "*"
  ks: ["*"]

explainer:
  name: shap
  tri_pipeline: ../../../netscratch/yay/tri_pipelines/tab/tab__lr1e-4__bs16__ft15__pre1
  risk_temperature: 0.1

precomputation:
  risk_scores: data/TAB/test_risk_shap.jsonl

tri_chunking:
  enabled: true

token_selection:
  name: until_k

sort_tokens_by_risk: false