params:
  epsilon: "*"
  rhos: ["*"]

explainer:
  name: shap
  tri_pipeline: ../../../netscratch/yay/tri_pipelines/tab/_checkpoints/task_{task_id}/tab__deid__lr5e-5__task_{task_id}
  risk_temperature: 0.1

precomputation:
  risk_scores: data/TAB/test_risk_shap.jsonl
  result_in: outputs/tab/presidio/{run_timestamp}_tab_presidio_task_{task_id}.jsonl

tri_chunking:
  enabled: true

token_selection:
  name: by_risk