add_probability: 0.0
delete_probability: 0.0

explainer:
  name: shap
  tri_pipeline: ../../../netscratch/yay/tri_pipelines/tab/20251201_092739
  risk_scores: data/TAB/test_risk_shap.jsonl
  risk_temperature: 0.1

tri_chunking:
  enabled: true
