params:
  epsilon: "*"
  lambdas: ["*"]

explainer:
  name: shap
  tri_pipeline: models/tri_pipelines/tab/20251110_183205
  risk_temperature: 0.1

precomputation:
  risk_scores: data/TAB/test_risk_shap.jsonl

tri_chunking:
  enabled: true

token_selection:
  name: pii_only
  pii_annotator: models/pii_detectors/tab/20251021_093003

pii_chunking:
  enabled: true