params:
  epsilon: "*"
  lambdas: ["05*", "09*"]

explainer:
  name: shap
  tri_pipeline: ../../../netscratch/yay/tri_pipelines/tab/_checkpoints/full/full
  risk_temperature: 0.1

precomputation:
  risk_scores: data/tab/tri_risk/shap_{task_id}.jsonl
  result_in: ../../../netscratch/yay/_ext_outputs/tab/presidio/{run_timestamp}_tab_presidio_task_{task_id}.jsonl

tri_chunking:
  enabled: true

token_selection:
  name: pii_only
  pii_annotator: ../../../netscratch/yay/pii_detectors/tab/tab__lr3e-5__bs8__m_partial_recall