params:
  epsilon: "*"
  rhos: ["*"]

explainer:
  name: shap
  tri_pipeline: ../../../netscratch/yay/tri_pipelines/tab/_checkpoints/500_random_{task_id}/500_random_{task_id}__task_{task_id}
  risk_temperature: 0.1

precomputation:
  risk_scores: data/tab/tri_risk/shap_{task_id}.jsonl
  result_in: outputs/tab/presidio/{run_timestamp}_tab_presidio_task_{task_id}.jsonl

tri_chunking:
  enabled: true

token_selection:
  name: by_risk