params:
  epsilon: "*"

explainer:
  name: shap
  tri_pipeline: models/tri_pipelines/tab/new_pipeline
  risk_temperature: 0.1

precomputation:
  risk_scores: data/TAB/test_risk_shap.jsonl

tri_chunking:
  enabled: true
  sort_by_risk: false