dataset: reddit
data_in: data/reddit
annotations_in:
  - outputs/reddit
metric:
  type: cosine
  vectorizer:
    type: sentence
    model_name: sentence-transformers/all-MiniLM-L6-v2
output:
output:
  format: jsonl
  file: logs/divergence/reddit/cosine.jsonl
