params:
  ks: ["*"]

explainer:
  name: greedy
  tri_pipeline: ../../../netscratch/yay/tri_pipelines/tab/20251203_134320

precomputation:
  risk_scores: data/TAB/test_risk_greedy.jsonl

mask_text: "[MASK]"

tri_chunking:
  enabled: false
