params:
  epsilon: "*"

T: 5

precomputation:
  risk_scores: data/tab/tri_risk/shap_subset.jsonl
  result_in: ../../../netscratch/yay/_ext_outputs_subset/tab/presidio/{run_timestamp}_tab_presidio.jsonl

explainer:
  name: shap
  tri_pipeline: ../../../netscratch/yay/tri_pipelines/tab/_checkpoints/full/full
  risk_temperature: 0.1

dpmlm_chunking:
  enabled: true
  max_tokens: 256
  overlap_tokens: 128

verbose: true
