params:
  epsilon: "*"
  ks: ["*"]

T: 5

precomputation:
  result_in: ../../../netscratch/yay/_ext_outputs/tab/presidio/{run_timestamp}_tab_presidio.jsonl

explainer:
  name: shap
  tri_pipeline: ../../../netscratch/yay/tri_pipelines/tab/_checkpoints/full/full
  risk_temperature: 0.1

utility_explainer:
  tri_pipeline: ../../../netscratch/yay/utility_pipelines/tab/_checkpoints/full/full
  alpha: 1.0

dpmlm_chunking:
  enabled: true
  max_tokens: 256
  overlap_tokens: 128

token_selection:
  name: until_k

verbose: true
