params:
  epsilon: "*"

refresh_interval: 1

explainer:
  name: shap
  tri_pipeline: ../../../netscratch/yay/tri_pipelines/tab/_checkpoints/full/full
  risk_temperature: 0.1

dpmlm_chunking:
  enabled: true
  max_tokens: 256
  overlap_tokens: 128
