dataset: reddit
data_in: data/reddit/reddit.jsonl
explainer: shap
explainer_in: ../../../netscratch/yay/tri_pipelines/reddit/_checkpoints/task_{task_id}/reddit__deid__lr5e-5__task_{task_id}
result_in: outputs/reddit/presidio/{run_timestamp}_reddit_presidio_task_{task_id}.jsonl
save_to_jsonl: data/reddit/tri_risk/shap_{task_id}.jsonl
sort_by: scores
offset_mode: original
