dataset: db_bio
data_in: data/db_bio
split: indices/db_bio/test/50_eval/{task_id}.txt
annotations_in:
  - outputs/db_bio
tri:
  universal_tri_pipeline: ../../../netscratch/yay/tri_pipelines/db_bio/_checkpoints/500_random_{task_id}/500_random_{task_id}__task_{task_id}
  max_length: 512
mask_token: "[MASK]"
output:
  format: jsonl
  file: logs/db_bio_priv_more_exp_task_{task_id}.jsonl
progress: false
