dataset: reddit
data_in: data/reddit/train.jsonl
debug: true
annotations_in:
  - outputs/reddit
target:
  key: feature_label
  type: nominal
selection_criteria:
  feature: city_country
group_by: hardness
split:
  - train: 0.0
    val: 1.0
  - path: data/reddit/synthetic_dataset.jsonl
    train: 1.0
    val: 0.0
random_state: 42
include_confusion_matrix: true
head:
  type: bert_classifier
  params:
    epochs: 40
    batch_size: 4
    model_name: distilbert-base-uncased
    init_checkpoint: ../../../netscratch/yay/tri_pipelines/reddit/_checkpoints/reddit_8_16_0.0001/finetuning/checkpoint-297
    checkpoint_dir: ../../../netscratch/yay/util_tri_pipelines/reddit/city_country
    primary_metric: macro_f1
    encoder_lr: 1e-6
    head_lr: 1e-3
    early_stop_patience: 3
output:
  format: jsonl
  file: logs/reddit_city_country_exp.jsonl
