dataset: reddit
data_in: data/reddit/reddit.jsonl
debug: true
annotations_in:
- outputs/reddit
target:
  key: feature_label
  type: ordinal
  enum:
  - 'sex: female'
  - 'sex: male'
selection_criteria:
  feature: sex
group_by: hardness
random_state: 42
include_confusion_matrix: true
head:
  type: logistic_classifier
  params:
    max_iter: 500
    class_weight: balanced
    n_jobs: -1
    primary_metric: f1
output:
  format: jsonl
  file: logs/internal_utility/reddit_sex.jsonl
protocol: internal_utility
internal_utility:
  n_folds: 50
vectorizer:
  type: tfidf
  params:
    ngram_range:
    - 1
    - 2
    max_features: 10000
    min_df: 2
