dataset: reddit
data_in: data/reddit/reddit.jsonl
debug: true
annotations_in:
- outputs/reddit
target:
  key: feature_label
  type: nominal
selection_criteria:
  feature: occupation
group_by: hardness
random_state: 42
include_confusion_matrix: true
head:
  type: bert_classifier
  params:
    epochs: 40
    batch_size: 4
    model_name: distilbert-base-uncased
    init_checkpoint: ../../../netscratch/yay/tri_pipelines/reddit/_checkpoints/sum_{task_id}/reddit_8_16_0.0001__task_{task_id}/finetuning/{checkpoint}
    checkpoint_dir: ../../../netscratch/yay/util_tri_pipelines/reddit/occupation_internal_utility
    primary_metric: macro_f1
    encoder_lr: 1e-6
    head_lr: 1e-3
    early_stop_patience: 3
    save_checkpoints: false
output:
  format: jsonl
  file: logs/utility/reddit/occupation_task_{task_id}.jsonl
protocol: internal_utility
internal_utility:
  n_folds: 50
vectorizer:
  type: text
