params:
  ks: ["*"]

explainer:
  name: shap
  tri_pipeline: ../../../netscratch/yay/tri_pipelines/db_bio/_checkpoints/50_eval_{task_id}/50_eval_{task_id}__task_{task_id}

precomputation:
  risk_scores: data/db_bio/tri_risk/shap_{task_id}.jsonl
  result_in: outputs/db_bio/presidio/{run_timestamp}_db_bio_presidio_task_{task_id}.jsonl

tri_chunking:
  enabled: true

token_selection:
  name: until_k
