params:
  ks: ["*"]

explainer:
  name: shap
  tri_pipeline: ../../../netscratch/yay/tri_pipelines/db_bio/db_bio__lr5e-5__eval

precomputation:
  risk_scores: data/db_bio/db_bio_risk_shap.jsonl
  result_in: outputs/db_bio/presidio/20260122_125715_db_bio_presidio.jsonl

tri_chunking:
  enabled: true

token_selection:
  name: until_k
