dataset: tab
data_in: data/TAB/splitted/test.json
annotations_in:
  - outputs/tab
tri:
  universal_tri_pipeline: ../../../netscratch/yay/tri_pipelines/tab/_checkpoints_realistic/tab__realistic__binary__lr5e-5
  max_length: 512
mask_token: "[MASK]"
output:
  format: jsonl
  file: logs/tab_priv_exp_realistic_binary.jsonl
progress: false
