dataset: tab
data_in: data/tab
split: indices/tab/test/50_eval/{task_id}.txt
annotations_in:
  - outputs/tab
metric:
  type: bertscore
  model_type: roberta-large
  batch_size: 8
output:
output:
  format: jsonl
  file: logs/divergence/tab/bertscore_task_{task_id}.jsonl
