dataset: tab
data_in: data/tab
split: indices/tab/test/50_eval/{task_id}.txt
annotations_in:
  - ../../../netscratch/yay/_ext_outputs/tab
metric:
  type: cosine
  vectorizer:
    type: sentence
    model_name: sentence-transformers/all-MiniLM-L6-v2
output:
output:
  format: jsonl
  file: logs/divergence/tab/cosine_task_{task_id}.jsonl
