dataset: tab
data_in: data/tab
annotations_in:
  - ../../../netscratch/yay/_ext_outputs/tab/baroud
  - ../../../netscratch/yay/_ext_outputs/tab/dpmlm
  - ../../../netscratch/yay/_ext_outputs/tab/manual
  - ../../../netscratch/yay/_ext_outputs/tab/petre
  - ../../../netscratch/yay/_ext_outputs/tab/presidio
  - ../../../netscratch/yay/_ext_outputs/tab/risk
  - ../../../netscratch/yay/_ext_outputs/tab/spacy
metric:
  type: pp
output:
  format: jsonl
  file: logs/divergence/tab/pp.jsonl
