epsilon: 10.0

model_checkpoint: roberta-base

explainer:
  name: greedy
  tri_pipeline: ../../../netscratch/yay/tri_pipelines/tab/20251203_134320
  risk_scores: data/TAB/test_risk_greedy.jsonl

tri_chunking:
  enabled: false

mask_text: "[MASK]"
