dataset: trustpilot
data_path: data/trustpilot/electronics+technology.csv
attacker_extensions: data/trustpilot/et_bk_deid.jsonl
model_name: distilbert-base-uncased
output_root: ../../../netscratch/yay/tri_pipelines/trustpilot/_checkpoints
max_records: null
max_length: 512
device: cpu

training:
  finetuning_epochs: 15
  batch_size: 32
  use_pretraining: true
  pretraining_epochs: 1
  per_step: null
  early_stop_threshold: null
