dataset: tab
data_in: data/tab
split: indices/tab/test.txt
debug: true
annotations_in:
  - ../../../netscratch/yay/_ext_outputs/tab/petre/*.jsonl
  - ../../../netscratch/yay/_ext_outputs/tab/dpmlm/*_shap_k*.jsonl
target:
  key: country_group
  type: nominal
source_splits:
  - split: indices/tab/train.txt
    train: 1.0
  - split: indices/tab/val.txt
    val: 1.0
random_state: 42
protocol: pseudo_utility
head:
  type: bert_classifier
  params:
    init_checkpoint: ../../../netscratch/yay/tri_pipelines/tab/_checkpoints/exact/exact/finetuning/{checkpoint}
    checkpoint_dir: ../../../netscratch/yay/util_tri_pipelines/tab/country
output:
  format: jsonl
  file: logs/pseudo_utility/tab/country_k.jsonl
