add_probability: 0.2
delete_probability: 0.1

explainer:
  name: greedy
  tri_pipeline: ../../../netscratch/yay/tri_pipelines/reddit/20251203_135444
  risk_scores: data/reddit/reddit_risk_greedy.jsonl
  risk_temperature: 0.1

tri_chunking:
  enabled: true
