params:
  epsilon: "*"
  rhos: ["*"]

explainer:
  name: shap
  tri_pipeline: models/tri_pipelines/reddit/20251110_190043
  risk_temperature: 0.1

precomputation:
  risk_scores: data/reddit/reddit_risk_shap.jsonl

tri_chunking:
  enabled: true

token_selection:
  name: by_risk
