params:
  epsilon: "*"

explainer:
  name: shap
  tri_pipeline: ../../../netscratch/yay/tri_pipelines/reddit/_checkpoints/exact/reddit_8_16_0.0001
  risk_temperature: 0.1

precomputation:
  risk_scores: data/reddit/tri_risk/shap.jsonl

tri_chunking:
  enabled: true
