params:
  epsilon: "*"
  ks: ["*"]

explainer:
  name: shap
  tri_pipeline: ../../../netscratch/yay/tri_pipelines/reddit/_checkpoints/sum_{task_id}/reddit_8_16_0.0001__task_{task_id}
  risk_temperature: 0.1

precomputation:
  risk_scores: data/reddit/tri_risk/shap_{task_id}.jsonl
  result_in: outputs/reddit/presidio/{run_timestamp}_reddit_presidio_task_{task_id}.jsonl

tri_chunking:
  enabled: true

token_selection:
  name: until_k