dataset: reddit
data_in: data/reddit/reddit.jsonl
annotations_in:
  - outputs/reddit
tri:
  universal_tri_pipeline: ../../../netscratch/yay/tri_pipelines/reddit/_checkpoints/reddit__lr5e-5
  max_length: 512
mask_token: "[MASK]"
output:
  format: jsonl
  file: logs/reddit_priv_exp.jsonl
progress: false
