params:
  ks: ["*"]

explainer:
  name: shap
  tri_pipeline: ../../../netscratch/yay/tri_pipelines/mimic/_checkpoints/full/full

precomputation:
  risk_scores: data/mimic/tri_risk/shap.jsonl
  result_in: ../../../netscratch/yay/_ext_outputs/mimic/presidio/{run_timestamp}_mimic_presidio.jsonl

token_selection:
  name: until_k
