params:
  epsilon: "*"
  ks: ["*"]

explainer:
  name: shap
  tri_pipeline: models/tri_pipelines/tab/20251110_183205
  risk_temperature: 0.1

precomputation:
  risk_scores: data/TAB/test_risk_shap.jsonl

starting_anonymizations:
  - outputs/reddit/presidio/20251216_160413_reddit_presidio.jsonl

tri_chunking:
  enabled: true

token_selection:
  name: until_k
  sort_by_risk: false