dataset: tab
data_in: data/tab
annotations_in:
  - ../../../netscratch/yay/_ext_outputs/tab/*iter*/*
metric:
  type: cosine
  vectorizer:
    type: sentence
    model_name: sentence-transformers/all-MiniLM-L6-v2
output:
  format: jsonl
  file: logs/divergence/tab/cosine.jsonl
