dataset: yelp
data_in: data/yelp/all.jsonl
explainer: shap
explainer_in: ../../../netscratch/yay/tri_pipelines/yelp/_checkpoints/yelp__deid__lr5e-5
result_in:
save_to_jsonl: data/yelp/yelp_risk_shap.jsonl
sort_by: scores
offset_mode: original
