data: reddit
data_in: data/reddit/reddit.jsonl
result_in: outputs/reddit/presidio/{run_timestamp}_reddit_presidio_task_{task_id}.jsonl
pipeline_in: ../../../netscratch/yay/tri_pipelines/reddit/_checkpoints/sum_{task_id}
n_first_predictions: 10