params:
  ks: ["*"]

T: .inf

precomputation:
  risk_scores: data/tab/tri_risk/shap.jsonl
  result_in: ../../../netscratch/yay/_ext_outputs/tab/presidio/{run_timestamp}_tab_presidio.jsonl

explainer:
  name: shap
  tri_pipeline: ../../../netscratch/yay/tri_pipelines/tab/_checkpoints/full/full

token_selection:
  name: until_k

verbose: true
